#!/bin/sh

# set the paths required for cuda
FILENAME="/etc/profile.d/xcat-cuda.sh"

echo "export PATH=/usr/local/cuda/bin:\$PATH" > ${FILENAME}
echo "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:\$LD_LIBRARY_PATH" >> ${FILENAME}
