#!/bin/sh

# set the paths required for cuda
CUDA_PATH=/usr/local/cuda
FILENAME="/etc/profile.d/xcat-cuda.sh"

echo "export PATH=$CUDA_PATH/bin:\$PATH" > ${FILENAME}
echo "export LD_LIBRARY_PATH=$CUDA_PATH/lib64:\$LD_LIBRARY_PATH" >> ${FILENAME}
