#!/bin/sh

name=`echo $NODE | awk -F- '{print $1}'`
if [ -z $name ]
then
name=$NODE
fi

for ((i=0;i<4;i++))
do
if [ $i = 0 ]
then
CLIENT_IP=`ping -c 3 $NODE | grep "data" | sed 's/.* (\([0-9.]*\)).*/\1/' | uniq 2>&1`
else 
CLIENT_IP=`ping -c 3 $name-hf$i | grep "data" | sed 's/.* (\([0-9.]*\)).*/\1/' | uniq 2>&1`
fi

if [ -n $CLIENT_IP ]
then
echo "DEVICE=hf$i
NM_CONTROLLED=yes
IPADDR=$CLIENT_IP
NETMASK=255.0.0.0
ONBOOT=yes
" >/etc/sysconfig/network-scripts/ifcfg-hf$i

ifup hf$i
sleep 1
fi

done
