#!/bin/ksh
# IBM(c) 2007 EPL license http://www.eclipse.org/legal/epl-v10.html
#egan@us.ibm.com
#(C)IBM Corp
#

if [ -r /etc/ssh/sshd_config ]
then
	logger -t xcat "Install: setup /etc/ssh/sshd_config"
	cp /etc/ssh/sshd_config /etc/ssh/sshd_config.ORIG
	perl -pi -e 's/^X11Forwarding .*$/X11Forwarding yes/' /etc/ssh/sshd_config
	perl -pi -e 's/^KeyRegenerationInterval .*$/KeyRegenerationInterval 0/' /etc/ssh/sshd_config
	perl -pi -e 's/(.*MaxStartups.*)/#\1/' /etc/ssh/sshd_config
	echo "MaxStartups 1024" >>/etc/ssh/sshd_config
	echo "PasswordAuthentication no" >>/etc/ssh/sshd_config
fi

if [ -d /xcatpost/.ssh ]
then
	logger -t xcat "Install: setup root .ssh"
	cd /xcatpost/.ssh
	mkdir -p /root/.ssh
	cp -f * /root/.ssh
	chmod 700 /root/.ssh
	chmod 600 /root/.ssh/*
fi
if [ -d /xcatpost/hostkeys ]
then
	logger -t xcat "Install: using server provided host key for convenience."
	cp /xcatpost/hostkeys/*_key /etc/ssh/
fi


exit 0

