#!/usr/bin/perl
# IBM(c) 2007 EPL license http://www.eclipse.org/legal/epl-v10.html
#egan@us.ibm.com
#(C)IBM Corp

#


#-----------------------------------------------------------------------------

=head1   servicenode 

 This updates the service node with files necessary to access the 
 database on the MasterNode and restarts the xcat daemon

=cut

#-----------------------------------------------------------------------------

# if this is a service node
#
#  Copy Certificates, and config file to apprpriate directories from mounted
#
if (-e "/etc/xCATSN")
{
    `/opt/xcat/sbin/copycerts`;
}

exit 0;


