#!/bin/sh
# IBM(c) 2007 EPL license http://www.eclipse.org/legal/epl-v10.html
#####################################################
#
#   Generic xCAT post script for diskless nodes
#
#####################################################
if [ ! `uname` == Linux ]; then
   MYDIR=`dirname $0`
   exec $MYDIR/xcatdsklspost.aix
   exit
fi
let SLI=$RANDOM%10
sleep $SLI

SIP=`grep -h dhcp-server-identifier /var/lib/dhclient/dhclient-*.leases|tail -n 1|awk '{print $3}'|sed -e 's/;//'`
if [ -z "$SIP" ]; then
    SIP=`grep -h DHCPSID /var/lib/dhcpcd/*.info|awk -F= '{print $2}'|tail -n 1`
fi

#echo "SIP=$SIP"
    
if grep 'rw /rw tmpfs ' /proc/mounts  >& /dev/null; then
    touch /var/lock/subsys/xcatmounts
    echo '#!/bin/bash' > /etc/rc6.d/K10xcatmounts
    echo umount -l /ro >> /etc/rc6.d/K10xcatmounts
    echo umount -l /rw >> /etc/rc6.d/K10xcatmounts
    chmod 755 /etc/rc6.d/K10xcatmounts
    ln -sf /etc/rc6.d/K10xcatmounts /etc/rc0.d/K10xcatmounts
fi


mkdir -p /etc/stunnel
mkdir -p /var/stunnel
cat > /etc/stunnel/stunnel.conf << EOF
client=yes
foreground=no
output=/dev/null
#output=/var/log/stunnel.log
verify=0
[xcatd]
accept=400
EOF
echo "connect=$SIP:3001" >> /etc/stunnel/stunnel.conf
stunnel; 
sleep 1; 
mkdir -p /xcatpost; 
mkdir -p /tmp/postage
rm -R -f /xcatpost/*
rm -R -f /tmp/postage/*

cd /tmp/postage
#wget -l inf -N -r --waitretry=10 --random-wait --retry-connrefused -t 0 -T 60 ftp://$SIP/install/postscripts 2> /tmp/wget.log
wget -l inf -N -r --waitretry=10 --random-wait --retry-connrefused -t 0 -T 60 ftp://$SIP/postscripts 2> /tmp/wget.log
#mv $SIP/install/postscripts/* /xcatpost; 
mv $SIP/postscripts/* /xcatpost; 
rm -rf $SIP
cd /xcatpost; 
PATH=/xcatpost:$PATH
export PATH
chmod +x /xcatpost/*;
echo "PATH=$PATH" 
/xcatpost/getpostscript.awk | sed  -e 's/<[^>]*>//g'|egrep -v '^ *$'|sed -e 's/^ *//' >  /tmp/mypostscript; 
MYCONT=`cat /tmp/mypostscript`
#echo "MYCONT=$MYCONT"
while [ -z "$MYCONT" ]; do
    let SLI=$RANDOM%10
    let SLI=10+$SLI
    sleep $SLI
    /xcatpost/getpostscript.awk | sed  -e 's/<[^>]*>//g'|egrep -v '^ *$'|sed -e 's/^ *//' >  /tmp/mypostscript; 
    MYCONT=`cat /tmp/mypostscript`
#    echo "MYCONT=$MYCONT"
done
if [ $# -gt 1 ]; then
  POSTS=$2
  #remove all the postscripts
  TMP=`sed "/postscripts-start-here/,/postscripts-end-here/ d" /tmp/mypostscript`
  echo "$TMP" > /tmp/mypostscript
  #add requested postscripts in
  echo "$POSTS" | tr "," "\n" >> /tmp/mypostscript
fi
#MYCONT=`cat /tmp/mypostscript`
#echo "$MYCONT"

if [ $# -eq 0 ]; then
  #notify the server that we are done with netbooting
  echo "updateflag.awk \$MASTER 3002 netbooted" >> /tmp/mypostscript
fi

chmod +x /tmp/mypostscript
if [ -x /tmp/mypostscript ];then
   /tmp/mypostscript
fi
rm -f /tmp/mypostscript

killall stunnel
rm -rf /etc/stunnel









