#!/bin/sh 
#usage:
#runcmdinstaller: issue command which run in the installer and print the command output
#runcmdinstaller <node> "<command>"


awk  -v argc="$#" -v node="$1" -v cmd="$2" 'BEGIN {
port = 3001
action = "sh"
if( node=="-h" || argc !=2 || ! node || ! cmd){
  print "Usage:\n\n   runcmdinstaller <node> \"<command>\"\n"
  print           "   make sure all the commands are quoted by \"\"\n";
  exit 1;
}

ns = "/inet/tcp/0/" node "/" port

#print "sh " |& ns
print action " " cmd " " |& ns

while((ns |& getline) > 0)
print $0

close(ns)

exit 0
}'
