#!/bin/sh

OSNAME=$(uname)
VER=`cat Version`

if [ "$OSNAME" = "AIX" ]
then

        #source=$PWD
        #cd /opt/freeware/src/packages/SOURCES
        #rm -f perl-xCAT-$VER; ln -s $source/perl-xCAT perl-xCAT-$VER
        #rm -f /opt/freeware/src/packages/SRPMS/perl-xCAT*rpm /opt/freeware/src/packages/RPMS/ppc/perl-xCAT*rpm
        #echo '.svn' > /tmp/xcat-excludes
        #tar -X /tmp/xcat-excludes -cf perl-xCAT-$VER.tar perl-xCAT-$VER
        #gzip -f /opt/freeware/src/packages/SOURCES/perl-xCAT-$VER.tar
        #cd $source/perl-xCAT
        #rpm -ba perl-xCAT.spec
        
        svn info > perl-xCAT/.svninfo
        source=/opt/freeware/src/packages
        echo '.svn' > /tmp/xcat-excludes
        tar -X /tmp/xcat-excludes -cf $source/SOURCES/perl-xCAT-$VER.tar perl-xCAT
        gzip -f $source/SOURCES/perl-xCAT-$VER.tar
        rm perl-xCAT/.svninfo
        rm -f $source/SRPMS/perl-xCAT*rpm $source/RPMS/ppc/perl-xCAT*rpm
        rpm -ba perl-xCAT/perl-xCAT.spec
        #rpm -ta $source/SOURCES/perl-xCAT-$VER.tar.gz
else

	rpmbuild --version > /dev/null
	if [ $? -gt 0 ]
	then
		echo "Error: Is rpmbuild installed and working?"
		exit 1
	fi
	RPMROOT=`rpmbuild --eval '%_topdir' xCATsn/xCATsn.spec`
	if [ $? -gt 0 ]
	then
		echo "Could not determine rpmbuild's root"
		exit 1
	fi
	echo "The location for rpm building is ${RPMROOT}"

	set -x
	
	svn info > perl-xCAT/.svninfo
	tar  --exclude .svn -czhf $RPMROOT/SOURCES/perl-xCAT-$VER.tar.gz perl-xCAT;
	rm perl-xCAT/.svninfo
	rm -f $RPMROOT/SRPMS/perl-xCAT-$VER*rpm $RPMROOT/RPMS/noarch/perl-xCAT-$VER*rpm
	rpmbuild -ta $RPMROOT/SOURCES/perl-xCAT-$VER.tar.gz
	
fi
