#@TYPE: Machine
#@NAME: xCAT Genesis armv7hf
#@DESCRIPTION: ARMv7-A hard-float Genesis target

DEFAULTTUNE = "armv7ahf"
ARM_INSTRUCTION_SET = "arm"
XCAT_GENESIS_ARCHITECTURE = "armv7hf"
require conf/machine/include/arm/arch-armv7a.inc
require conf/machine/include/qemu.inc

KERNEL_IMAGETYPE = "zImage"
SERIAL_CONSOLES = "115200;ttyAMA0"
XCAT_GENESIS_CONSOLE_TTY = "ttyAMA0"

MACHINE_FEATURES_DEFAULTS = ""
MACHINE_FEATURES = "pci"
MACHINE_ESSENTIAL_EXTRA_RDEPENDS = ""
MACHINE_EXTRA_RRECOMMENDS = ""

IMAGE_FSTYPES = "cpio.gz ext4"

QB_SYSTEM_NAME = "qemu-system-arm"
QB_MACHINE = "-machine virt,highmem=off"
QB_CPU = "-cpu cortex-a15"
QB_SMP = "-smp 2"
QB_DEFAULT_FSTYPE = "ext4"
QB_KERNEL_CMDLINE_APPEND = "console=ttyAMA0"
QB_OPT_APPEND = ""
