#@TYPE: Machine
#@NAME: xCAT Genesis riscv64
#@DESCRIPTION: RV64GC Genesis target

DEFAULTTUNE = "riscv64"
XCAT_GENESIS_ARCHITECTURE = "riscv64"
require conf/machine/include/riscv/qemuriscv.inc

KERNEL_IMAGETYPE = "Image"
KERNEL_IMAGETYPES = ""
SERIAL_CONSOLES = "115200;ttyS0"
XCAT_GENESIS_CONSOLE_TTY = "ttyS0"

MACHINE_FEATURES_DEFAULTS = ""
MACHINE_FEATURES = "pci"
MACHINE_ESSENTIAL_EXTRA_RDEPENDS = ""
MACHINE_EXTRA_RRECOMMENDS = ""

IMAGE_FSTYPES = "cpio.gz ext4"
EXTRA_IMAGEDEPENDS = "opensbi"
RISCV_SBI_PLAT = "generic"

QB_SYSTEM_NAME = "qemu-system-riscv64"
QB_MACHINE = "-machine virt"
QB_CPU = "-cpu rv64"
QB_SMP = "-smp 2"
QB_DEFAULT_BIOS = "fw_jump.elf"
QB_DEFAULT_FSTYPE = "ext4"
QB_KERNEL_CMDLINE_APPEND = "console=ttyS0 earlycon=sbi"
QB_OPT_APPEND = ""
