#@TYPE: Machine
#@NAME: xCAT Genesis aarch64
#@DESCRIPTION: Generic ARMv8-A Genesis target

DEFAULTTUNE = "aarch64"
XCAT_GENESIS_ARCHITECTURE = "aarch64"
require conf/machine/include/arm/arch-arm64.inc
require conf/machine/include/qemu.inc

KERNEL_IMAGETYPE = "Image"
SERIAL_CONSOLES = "115200;ttyAMA0"
XCAT_GENESIS_CONSOLE_TTY = "ttyAMA0"

MACHINE_FEATURES_DEFAULTS = ""
MACHINE_FEATURES = "pci"
MACHINE_ESSENTIAL_EXTRA_RDEPENDS = ""
MACHINE_EXTRA_RRECOMMENDS = ""

IMAGE_FSTYPES = "cpio.gz ext4"

QB_SYSTEM_NAME = "qemu-system-aarch64"
QB_MACHINE = "-machine virt"
QB_CPU = "-cpu cortex-a57"
QB_SMP = "-smp 2"
QB_DEFAULT_FSTYPE = "ext4"
QB_KERNEL_CMDLINE_APPEND = "console=ttyAMA0"
QB_OPT_APPEND = ""
