#@TYPE: Machine
#@NAME: xCAT Genesis x86_64
#@DESCRIPTION: x86_64-v1 Genesis target

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
RDEPENDS:${KERNEL_PACKAGE_NAME}-base = ""

DEFAULTTUNE = "x86-64"
XCAT_GENESIS_ARCHITECTURE = "x86_64"
require conf/machine/include/x86/arch-x86.inc
require conf/machine/include/x86/qemuboot-x86.inc

KERNEL_IMAGETYPE = "bzImage"
SERIAL_CONSOLES = "115200;ttyS0"
XCAT_GENESIS_CONSOLE_TTY = "ttyS0"

MACHINE_FEATURES_DEFAULTS = ""
MACHINE_FEATURES = "pci"
MACHINE_EXTRA_RRECOMMENDS = ""

IMAGE_FSTYPES = "cpio.gz ext4"

QB_SYSTEM_NAME = "qemu-system-x86_64"
QB_DEFAULT_FSTYPE = "ext4"
QB_CPU:x86-64 = "-cpu qemu64 -machine q35,i8042=off"
QB_CPU_KVM:x86-64 = "-cpu qemu64 -machine q35,i8042=off"
QB_KERNEL_CMDLINE_APPEND = "console=ttyS0"
