# IBM(c) 2007 EPL license http://www.eclipse.org/legal/epl-v10.html
package xCAT_schema::kvm_nodedata;

###############################################################################
# This is a table for kvm plugin to use to maintain persistent config data
# not feasibly determined from contextual data
###############################################################################
%tabspec = (
    kvm_nodedata => {      
	cols => [qw(node xml comments disable)], 
	keys => [qw(node)],
        required => [qw(node xml)],
	table_desc => 'Persistant store for KVM plugin, not intended for human modification.',
	descriptions => {
        node => 'The node corresponding to the virtual machine',
        xml => 'The XML description generated by xCAT, fleshed out by libvirt, and stored for reuse',
	    comments => 'Any user-written notes.',
	    disable => "Set to 'yes' or '1' to comment out this row.",
	},
    },
); # end of tabspec definition

#Since this is only used by a plugin and not intended for human consumption,
#the defspecs are skipped

1;


