#!/bin/bash
set -eu

request=
IFS= read -r request || true
if [[ $request != *CREDOKBYYOU?* ]]; then
    logger -t xcat-genesis-credential-callback -- \
        'ignored an invalid credential check'
    exit 1
fi

printf '%s\n' CREDOKBYME
