#!/bin/bash

BASE_DIR="${0%/*}"

! source "${BASE_DIR}/functions.sh" >/dev/null 2>&1 &&
        echo "File \"${BASE_DIR}/functions.sh\" not found" >&2 && exit 1

make_bogus_ppc64_osimage
make_bogus_grub2_nodes

function custom_cleanup()
{
	destory_bogus_nodes
	destory_bogus_osimages
}

chdef tz003 arch=
nodeset tz001+4 shell
# Check $? != 0
[ "$?" -ne "0" ]
exit_if_bad "$?" "nodeset command should exit with non-zero"

# Make sure all other nodes are good
for node in tz001 tz002 tz004 tz005
do
	[ -f "/tftpboot/petitboot/${node}" ]
	exit_if_bad "$?" "file not found /tftpboot/petitboot/${node}" 
done

nodeset tz001+4 offline

exit 0
