#!/bin/sh

if [[ ! -z "$installroot" ]]; then
    if [ -n "`ls $installroot/opt/xcat/kits/gpfs/min_gpfs_compute-3.5.0-7-rhels-6-ppc64/*.rpm 2> /dev/null`" ] ; then
        rpm --force --root $installroot -Uvh $installroot/opt/xcat/kits/gpfs/min_gpfs_compute-3.5.0-7-rhels-6-ppc64/*.rpm
    fi
else
    if [ -n "`ls /opt/xcat/kits/gpfs/min_gpfs_compute-3.5.0-7-rhels-6-ppc64/*.rpm 2> /dev/null`" ] ; then
        rpm --force -Uvh /opt/xcat/kits/gpfs/min_gpfs_compute-3.5.0-7-rhels-6-ppc64/*.rpm
    fi
fi

exit 0
