#!/bin/sh

# 
# Sample script to accept licenses for the IBM vacpp and xlf compilers
# For AIX:
#    do nothing, license accepted with installp -Y flag
# For Linux:
#    Assumes all compiler software has been installed


OS=`uname`
if [ $OS != "AIX" ]; then
    vacpp_script=`find /opt/ibmcmp/vacpp -name new_install -print`

   if [ -n "$vacpp_script" ] ; then
       echo 1 | $vacpp_script
   fi

fi  


