#!/bin/sh
# IBM(c) 2007 EPL license http://www.eclipse.org/legal/epl-v10.html
# chkconfig: 345 85 60
# description: xCAT management service
# processname: xcatd

### BEGIN INIT INFO
# Provides: xcatd
# Required-Start: $network $syslog 
# Required-Stop: 
# Should-Start: mysql
# Default-Start: 3 4 5
# Default-stop: 0 1 2 6
# Short-Description: xcatd
# Description: xCAT management service
### END INIT INFO

RHSuccess()
{
    success
    echo
}

RHFailure()
{
    failure
    echo
}

if [ -f /etc/init.d/functions ]; then
  #echo RH
  . /etc/init.d/functions
  START_DAEMON=daemon
  LOG_SUCCESS=RHSuccess
  LOG_FAILURE=RHFailure
  LOG_WARNING=passed
elif [ -f /lib/lsb/init-functions ]; then
  . /lib/lsb/init-functions
  START_DAEMON=start_daemon
  LOG_SUCCESS=log_success_msg
  LOG_FAILURE=log_failure_msg
  LOG_WARNING=log_warning_msg
else
  echo "Error, don't know how to start on this platform"
  exit 1
fi

if [ -r /etc/profile.d/xcat.sh ]; then
       . /etc/profile.d/xcat.sh
fi
case $1 in
restart)
  echo -n "Restarting xcatd "
  xcatctl restart > /dev/null && $LOG_SUCCESS || $LOG_FAILURE
  ;;
reload)
  echo -n "Reloading xcatd "
  xcatctl reload > /dev/null && $LOG_SUCCESS || $LOG_FAILURE
  ;;
status)
  xcatctl status
  ;;
stop)
  echo -n "Stopping xcatd "
  xcatctl stop > /dev/null && $LOG_SUCCESS || $LOG_FAILURE
  ;;
start)
  xcatctl status >/dev/null 2>&1
  if [ "$?" = "0" ]; then
    echo -n "xcatd already running "
    $LOG_WARNING
    echo
    exit
  fi
  echo -n "Starting xcatd "
  xcatctl start > /dev/null && $LOG_SUCCESS || $LOG_FAILURE
  ;;
esac
