DISTRO = "xcat-genesis"
DISTRO_NAME = "xCAT Genesis"
DISTRO_VERSION = "0.1"
DISTRO_CODENAME = "cheetah"
LINUX_VERSION_EXTENSION = "-xCAT-genesis"
KERNEL_MODULE_PACKAGE_SUFFIX = "-${KERNEL_VERSION_PKG_NAME}"

TCLIBC = "glibc"
INIT_MANAGER = "systemd"

DISTRO_FEATURES_DEFAULTS = ""
DISTRO_FEATURES = "acl ipv4 ipv6 largefile pci seccomp"

PACKAGE_CLASSES = "package_ipk"
VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""
VIRTUAL-RUNTIME_login_manager = "busybox"

NO_RECOMMENDATIONS = "1"

PACKAGECONFIG:pn-systemd = "acl kmod link-udev-shared randomseed seccomp set-time-epoch sysext sysusers zstd"
RDEPENDS:systemd:remove = "systemd-serialgetty util-linux-agetty"

PACKAGECONFIG:pn-networkmanager = "crypto-null libedit man-resolv-conf nmcli systemd"
PACKAGECONFIG:append:pn-iproute2 = " rdma"
NETWORKMANAGER_DHCP_DEFAULT:pn-networkmanager = "internal"
NETWORKMANAGER_DNS_RC_MANAGER_DEFAULT:pn-networkmanager = "symlink"
NETWORKMANAGER_FIREWALL_DEFAULT:pn-networkmanager = ""
