loaddefault all
set CMOS_SerialA "Auto-Configure"
set CMOS_SerialB "Auto-Configure"
set CMOS_RemoteConsoleEnable "Enabled"
set CMOS_RemoteConsoleComPort "COM 1"
set CMOS_RemoteConsoleBaud "115200"
set CMOS_RemoteConsoleEmulation "VT100/VT220"
set CMOS_RemoteConsoleKybdEmul "VT100/VT220"
set CMOS_RemoteConsoleBootEnable "Enabled"
set CMOS_RemoteConsoleFlowCtrl "Hardware"
set CMOS_ENET2_PXE_ENABLE "Disabled"
set CMOS_ENET3_PXE_ENABLE "Disabled"
set CMOS_ENET4_PXE_ENABLE "Disabled"
set CMOS_PostBootFailRequired "Disabled"
set CMOS_ROMControlSlot1 "Disabled"
set CMOS_ROMControlSlot2 "Disabled"
set CMOS_IOMMU_PLANAR_ENABLE "Enabled"
