<?php

if(!isset($TOPDIR)) { $TOPDIR="..";}

require_once "$TOPDIR/lib/security.php";
require_once "$TOPDIR/lib/functions.php";
require_once "$TOPDIR/lib/display.php";
require_once "$TOPDIR/lib/monitor_display.php";

$mode = $_REQUEST['mode'];
$value = $_REQUEST['value'];
$nr = $_REQUEST['nr'];
//nr = "cluster" or "summary" or node name

if($mode == "text") {
    displayRMCMonshowAttr($value, $nr);
} elseif($mode == "graph") {
    //display the pictures generated by "rrdtool";
    //in the feture, the pictures will be generated by jQuery plug-ins;
    displayRMCMonshowGraph($value, $nr);
}


?>
