BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xcat_genesis"
BBFILE_PATTERN_xcat_genesis = "^${LAYERDIR}/"
BBFILE_PRIORITY_xcat_genesis = "10"

LAYERDEPENDS_xcat_genesis = "core"
LAYERSERIES_COMPAT_xcat_genesis = "wrynose"
