#@TYPE: Machine
#@NAME: xCAT Genesis ppc64
#@DESCRIPTION: Generic 64-bit big-endian PowerPC Genesis target

DEFAULTTUNE = "powerpc64"
XCAT_GENESIS_ARCHITECTURE = "ppc64"
require conf/machine/include/powerpc/arch-powerpc64.inc
require conf/machine/include/qemu.inc

MACHINEOVERRIDES =. "qemuppc64:"

KERNEL_IMAGETYPE = "vmlinux"
SERIAL_CONSOLES = "115200;hvc0"
XCAT_GENESIS_CONSOLE_TTY = "hvc0"

MACHINE_FEATURES_DEFAULTS = ""
MACHINE_FEATURES = "pci"
MACHINE_ESSENTIAL_EXTRA_RDEPENDS = ""
MACHINE_EXTRA_RRECOMMENDS = ""

IMAGE_FSTYPES = "cpio.gz ext4"

QB_SYSTEM_NAME = "qemu-system-ppc64"
QB_MACHINE = "-machine pseries"
QB_CPU = "-cpu POWER8"
QB_SMP = "-smp 2"
QB_DEFAULT_FSTYPE = "ext4"
QB_KERNEL_CMDLINE_APPEND = "console=hvc0 nohugevmalloc"
QB_OPT_APPEND = ""
