create db xcatdb;
connect to xcatdb;
CREATE BUFFERPOOL BP16K SIZE 2000 PAGESIZE 16K;
Create tablespace xcattbs16k pagesize 16k managed by system using('/var/lib/db2/ts16')  BUFFERPOOL BP16K;
CREATE BUFFERPOOL BP32K SIZE 2000 PAGESIZE 32K;
Create tablespace xcattbs32k pagesize 32k managed by system using('/var/lib/db2/ts32')  BUFFERPOOL BP32K;
update db cfg for xcatdb using MAXLOCKS AUTOMATIC;
update db cfg for xcatdb using LOCKLIST AUTOMATIC;
update db cfg for xcatdb using APPGROUP_MEM_SZ 40000;
update db cfg for xcatdb using GROUPHEAP_RATIO 80;
update db cfg for xcatdb using NUM_IOCLEANERS AUTOMATIC;
update db cfg for xcatdb using NUM_IOSERVERS AUTOMATIC;
update db cfg for xcatdb using SOFTMAX 120;
update db cfg for xcatdb using APP_CTL_HEAP_SZ 512;
update db cfg for xcatdb using DBHEAP AUTOMATIC;
update db cfg for xcatdb using SORTHEAP AUTOMATIC;
update db cfg for xcatdb using STMTHEAP AUTOMATIC;
update db cfg for xcatdb using APPLHEAPSZ AUTOMATIC;
update db cfg for xcatdb using DATABASE_MEMORY AUTOMATIC;
update db cfg for xcatdb using PCKCACHESZ AUTOMATIC;
update db cfg for xcatdb using SHEAPTHRES_SHR AUTOMATIC;
update db cfg for xcatdb using APPL_MEMORY AUTOMATIC;
update db cfg for xcatdb using STAT_HEAP_SZ AUTOMATIC;
update db cfg for xcatdb using DFT_PREFETCH_SZ AUTOMATIC;
update db cfg for xcatdb using MAXAPPLS AUTOMATIC;
update db cfg for xcatdb using AVG_APPLS AUTOMATIC;
update db cfg for xcatdb using LOGBUFSZ 98;
update db cfg for xcatdb using LOGFILSIZ 40048;
update db cfg for xcatdb using LOGPRIMARY 10;
update db cfg for xcatdb using LOGSECOND 20;
update db cfg for xcatdb using AUTO_RUNSTATS ON;
update db cfg for xcatdb using AUTO_TBL_MAINT ON;
update db cfg for xcatdb using AUTO_MAINT ON;
