update dbm cfg  using MON_HEAP_SZ AUTOMATIC;
update dbm cfg using INSTANCE_MEMORY AUTOMATIC;
update dbm cfg  using NUM_POOLAGENTS AUTOMATIC;
update dbm cfg using MAX_COORDAGENTS AUTOMATIC;
update dbm cfg using MAX_CONNECTIONS AUTOMATIC;
update dbm cfg using FENCED_POOL AUTOMATIC;
update dbm cfg using FCM_NUM_BUFFERS AUTOMATIC;
update dbm cfg using FCM_NUM_CHANNELS AUTOMATIC;
update dbm cfg using DIAGSIZE 1024;
