<?php
/* 
 * use the xCAT command "monshow" to display the current status for RMC Resources being monitored
 */

if(!isset($TOPDIR)) { $TOPDIR="..";}
require_once "$TOPDIR/lib/security.php";
require_once "$TOPDIR/lib/functions.php";
require_once "$TOPDIR/lib/display.php";
require_once "$TOPDIR/lib/monitor_display.php";

displayMapper(array('home'=>'main.php', 'monitor' =>''));

displayTips(array("Select the domain: the whole cluser or the compute nodes under \"<b>lpar</b>\",",
"then select the desired attributes. click the \"View by Text\" button or the \"View by Graphics\" button"));

insertDiv("rmc_tree");

?>

<script type="text/javascript">
    $(init_rmc_ositree());
</script>

<?php

echo "<div id='rmc_monshow'>";
echo "<div id='monshow_opt'></div>";
//if the user clicks the "View by Text" button, the div named "monshow_data" will show 
// the text data from the "monshow" command;
//and , if the "view by Graphics" button is clicked, the "monshow_data" div will display the pictures, the pictures is generated by "rrdtool" right now, but in the future, some jQuery plugin will be used to generate the graphics for the "monshow" data
echo "<div id='monshow_data'></div>";
echo "</div>";

?>
